import { Sometype_Mono } from 'next/font/google';
import './globals.css';
// Components
import MainNav from '@/components/MainNav';
import PageTransition from '@/components/pageTransition';
import RectangleTransition from '@/components/RectangleTransition';
import Gradient from '@/components/Gradient';
import Header from '@/components/Header';

const sometypeMono = Sometype_Mono({
	variable: '--font-sometype-mono',
	subsets: ['latin'],
});

export const metadata = {
	title: 'Portfolio',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang="es">
			<body
				className={`$ ${sometypeMono.variable} antialiased overflow-hidden relative`}
			>
				<Gradient />
				<RectangleTransition />
				<PageTransition>
					<div className="flex">
						{/* main nav */}
						<div
							className="hidden 2xl:flex w-[285px] h-screen
				 bg-secundary"
						>
							<MainNav />
						</div>
						<div
							className="w-full max-w-[1130px] px-[15px] mx-auto
				"
						>
							<Header />
							<div>{children}</div>
						</div>
					</div>
				</PageTransition>
			</body>
		</html>
	);
}
